version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
test: off
build_script:
  - ps: ./Build.ps1
artifacts:
  - path: artifacts\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: YSmZjTq4KgxY4YlLZm9utXH4FkBxVvfhTdLPhFoZ24YDyE+Re32Tg5p9Ra//euX1
  skip_symbols: true
  on:
    branch: /^(master|development)$/